### ISSUE TITLE
Bind package to app

### ISSUE THREAD

**Issue by hadley** [mpiccirilli/Rlinkedin#1]
There's no reason to require every use to create their own app. Just include the app key and secret in the package. (It's ok to do this - every other app does although it's usually somewhat obscured in a binary file)

**Comment by mpiccirilli** [comment]
This is a good point.  I will build this into the package in the next day or so.  Thanks Hadley!

**Comment by mpiccirilli** [comment]
@hadley I included an app key and secret key in the authentication function, so users can either use 'default keys' or their own keys w/ the same function.  It seems like sort of an elementary operation, but I'm not quite sure how else include the information.

**Comment by hadley** [comment]
I think that's a reasonable approach.

**Comment by mpiccirilli** [comment]
Great, thanks!
