### ISSUE TITLE
getMyConnections() broken?

### ISSUE THREAD

**Issue by hack-r** [mpiccirilli/Rlinkedin#12]
```
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.

> Rlinkedin::getMyConnections(token2)
Error in x.list[sapply(x.list, is.list)] <- NA : 
  invalid subscript type 'list'
```

**Comment by mpiccirilli** [comment]
@hack-r Please check the Readme.  This function is no longer available.  I've created a list of all the functions that are no longer available after LinkedIn changed their open API access on May 12, 2015.
