### ISSUE TITLE
getProfile with Id

### ISSUE THREAD

**Issue by sharattadimalla** [mpiccirilli/Rlinkedin#13]
Hi Michael,

I have been trying to use the id parameter in the getProfile function as a means to retrieve profile information for connections. But I have successfully authenticated and am able to retrieve my own profile info.

myProfile <- getProfile(in.auth)

However when I try to pass the id parameter, I am getting an error.

myProfile <- getProfile(in.auth, connections = FALSE, id = 1234567891234)

Error in x.list[sapply(x.list, is.list)] <- 0 : 
  invalid subscript type 'list'

It sounds like the public profile API supports the search of people using id.
https://developer-programs.linkedin.com/documents/profile-api

Any hints or guidance here is appreciated.

By the way you have come up with a super useful package.

**Comment by mpiccirilli** [comment]
@sharattadimalla Please check the Readme.  I've made a list of all the functions that are no longer available after LinkedIn changed the access to their open API on May 12, 2015.  The _connections_ and _id_ parameters for the **getProfile** function are the 2nd and 3rd on the **Not Available** list.

**Comment by sharattadimalla** [comment]
Thanks Michael. Appreciate you take the time.
I might potentially join LinkedIn's partner program, in which case would getMyConnections function work?
If not I might have to work with the curl & jsonlite to extract the information, so just wanted to confirm.
Sharat

**Comment by mpiccirilli** [comment]
You can apply for the Partners program but I don't think you'll get accepted unless you have a really good reason. I applied with the interest of just keeping the functions of this package updated but was rejected.  Let me know when you hear back from LinkedIn.  If you get accepted we can go from there. :)

**Comment by AndreaCirilloAC** [comment]
I don't know you, but I am a bit upset by this new partnership program...

Andrea Cirillo
+39 3486881826
Via Meriggia 32
Settimo Milanese (MI), 
20019, Italy
it.linkedin.com/in/cirilloandrea
andreacirilloblog.wordpress.com
