### ISSUE TITLE
Error installation  "dependency 'httr' is not available for package 'Rlinkedin'"

### ISSUE THREAD

**Issue by fmaume** [mpiccirilli/Rlinkedin#14]
Under R version 3.1.0 (2014-04-10) -- "Spring Dance" (windows)
Package httr was already installed.

Installation returned: 

Downloading GitHub repo mpiccirilli/Rlinkedin@master
Installing Rlinkedin
Installing 10 packages: digest, httpuv, httr, jsonlite, magrittr, mime, R6, Rcpp, stringr, XML
package ‘digest’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘digest’
package ‘httpuv’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘httr’
package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘magrittr’ successfully unpacked and MD5 sums checked
package ‘mime’ successfully unpacked and MD5 sums checked
package ‘R6’ successfully unpacked and MD5 sums checked
package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’
package ‘stringr’ successfully unpacked and MD5 sums checked
package ‘XML’ successfully unpacked and MD5 sums checked
"C:/PROGRA~1/R/R-31~1.0/bin/i386/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/fabian/AppData/Local/Temp/RtmpC4VcMy/devtoolscb82e32ca4/mpiccirilli-Rlinkedin-b131a4f"  \
  --library="C:/Users/fabian/Documents/R/win-library/3.1" --install-tests 

ERROR: dependency 'httr' is not available for package 'Rlinkedin'
- removing 'C:/Users/fabian/Documents/R/win-library/3.1/Rlinkedin'
  Error: Command failed (1)

**Comment by mpiccirilli** [comment]
Are you downloading from GitHub or from CRAN?

**Comment by zstaykova** [comment]
Hi,

I am not sure this is a relevant thread, but I receive the following error after (I think) successful authentication:
`in.auth <- inOAuth(application_name=app_name, consumer_key=client_id, consumer_secret=client_secret)
myGroups <-getGroups(in.auth)`

the error I receive is:
`Error in UseMethod("xmlRoot") : 
  no applicable method for 'xmlRoot' applied to an object of class "c('xml_document', 'xml_node')"`

I am new to R but I think all relevant packages installed properly. I am on suse leap if this matters

Thanks for all!
Zlatka

**Comment by mpiccirilli** [comment]
@zstaykova I know that `httr` was updated, I'll makes sure this isn't because of the update.

**Comment by mpiccirilli** [comment]
@zstaykova I must have been rushed when I responded to this -- I believe the problem is that LinkedIn no longer supports the endpoint the **getGroups()** function was calling.  If you go to the main readme of the package ([README](https://github.com/mpiccirilli/Rlinkedin)), you'll see that I have a list of functions that are and are not available after their changes in May 2015.

**Comment by mpiccirilli** [comment]
@zstaykova I've updated the functions on GitHub to notify users of functions that are no longer available.  I will send an update to CRAN this evening.
