### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by salahuddin1234** [mpiccirilli/Rlinkedin#15]
Hello there I am getting the following error while using the function. 

`getMyConnections(in.auth)
Error in UseMethod("xpathApply") : 
  no applicable method for 'xpathApply' applied to an object of class "c('xml_document', 'xml_node')"`

**Comment by salahuddin1234** [comment]
IT asked for the xml2 package. I installed it but still nothing happened.

**Comment by mpiccirilli** [comment]
@salahuddin1234 please see GitHub [README](https://github.com/mpiccirilli/Rlinkedin), LinkedIn took that endpoint away almost a year ago.

**Comment by Micseb** [comment]
Hi, got excatly the same issue and message. That problem is not solved.

**Comment by gmendesb** [comment]
I used xmlParse (content(x)) instead of content(x) and it worked

**Comment by mpiccirilli** [comment]
@gmendesb do you have a key under their partners program?
