### ISSUE TITLE
Authentication over shinyapps.io

### ISSUE THREAD

**Issue by debsush** [mpiccirilli/Rlinkedin#17]
Does the Rlinkedin authentication work over shinyapps.io.   I have tested locally and it works fine but I could not make it work when deployed over shinyapps.io and would appreciate some guidance.

Thank you
SD

**Comment by mpiccirilli** [comment]
@debsush is this the same issue you are experiencing with the facebook package (I see your posts on there too)?

**Comment by debsush** [comment]
Yes.  I was wondering if your app allows us to callback on any port (say 80) or reference a shinyapps link like https://dmarket.shinyapps.io/Main.  It seems shinyapps does not allow callback on port 1410 and this is a concern for my webapp deployed over shinyapps.io  
I would also like to point that the package googleAuthR works fine in shinyapps.io as it allows us to provide a callback URL of our choice.  Let me know how does it work with your package and if it allows authentication over shinyapps

**Comment by mpiccirilli** [comment]
You can set a redirect URL on your LinkedIn's application settings.  Have you tried that already?

**Comment by debsush** [comment]
I will try it tonight and keep you posted.

**Comment by debsush** [comment]
Hi,

I tried to build a shinyapp which should allow the users to login/authenticate using Linkedin but it did not yield the desired results

```
 shinyjs::onclick("LinkedinLogBtn",LinkedAuth())

  LinkedAuth <- reactive({
    in.auth <- inOAuth("GoCharting", "appID", "appSecret")
    my.profile <<- getProfile(in.auth)
  })

  output$user_name <- renderText({
    LinkedAuth()[[1]]["location"][[1]]
  })
```

I had entered the redirect URL as http://127.0.0.1:1221 and I executed my shinyapp on the port 1221.  Following pointers:
1. As soon as the App launches, the authentication script kicks in and requires us to press a key in RStudio.  Ideally on click of the Login Button, the authentication should execute and should not require any input on RStudio Console.
2.  I am not sure if the auth token is retained during the R session.  I think what would really help users of this package is if I demo can be provided as an example on how things will work on shiny.
Mark (creator of googleAuthR) has provided very simple demo apps which makes it very convenient for users like us to implement the package on shinyapps.  I am assuming some of the techniques used by his package could also be used here but I am not competent enough to make it happen.

Reference: https://github.com/MarkEdmondson1234/googleID

**Comment by mpiccirilli** [comment]
@debsush were you able to solve this?

**Comment by debsush** [comment]
I did try anymore

**Comment by mpiccirilli** [comment]
ok, I will close this.
