### ISSUE TITLE
Issue with authentication

### ISSUE THREAD

**Issue by nadavkun** [mpiccirilli/Rlinkedin#18]
Hi, 
I want to try the package using the default authentication, but I keep getting this error:

> in.auth <- inOAuth()
> If you've created you're own application, be sure to copy and paste the following into 
>  'OAuth 2.0 Redirect URLs' in the LinkedIn Application Details: http://localhost:1410/ 
>  When done, press any key to continue...
> Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
>   Forbidden (HTTP 403).

any idea why? 

Nadav

**Comment by lbertolotti** [comment]
I'm having the same issue. The problem is generated by the oauth1.0_token function in inOAuth():

```
token <- oauth1.0_token(linkedin, myapp)
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Forbidden (HTTP 403).
```

Maybe the "default credentials" aren't working at all.

**Comment by mpiccirilli** [comment]
@lbertolotti @nadavkun I just checked on this:  Yes, the default credentials need to be updated.  I will update the default credentials on GitHub now.

**Comment by mpiccirilli** [comment]
Just pushed the updated credentials d4f169c8495f3eb844cdbf1025897da967ead0d6 / 75bf385f6c4f5c29e6a6007c8ddafb37dee4b751.  I'm making a few other updates to the package an will push update to CRAN soon.
