### ISSUE TITLE
Having trouble with searchCompanies function

### ISSUE THREAD

**Issue by jonrobinson2** [mpiccirilli/Rlinkedin#19]
Hi, thanks for maintaining such a great package. I'm trying to use the searchCompanies function with a non-partner API key (for what it's worth)

When I run this query, it works just fine.

``` R
searchCompanies(token=in.auth, 
                               keywords = 'Linkedin')
```

But when I run this query, however it fails.

``` R
searchCompanies(token=in.auth, 
                               keywords = '33Across')
Error in searchCompanies(token = in.auth, keywords = "33Across") : 
  object 'q.list' not found
```

However when I run a query like this it works:

``` R
searchCompanies(token=in.auth, 
                               keywords = 'Pepsi')
```

Any rhyme or reason to this? I authenticated using OAuth2 using hte exact procedures you lay out in your README. Thanks!

**Comment by mpiccirilli** [comment]
@jonrobinson2 You may need to be more specific, however I don't experience the same issue. When I search for '33Across' I get three (3) results.  I am however updating the package for some updates of it's dependent pacakges.

**Comment by jonrobinson2** [comment]
Do you have the vanilla public API credentials or did your application to work with the more in depth access, private API?

**Comment by mpiccirilli** [comment]
I only have the plain vanilla public api access. I don't have access to the
partners program or private access to even upkeep the functions.
