### ISSUE TITLE
Authorization tokens

### ISSUE THREAD

**Issue by skyprince999** [mpiccirilli/Rlinkedin#2]
While running getMyConnections() I get the following error : 

Error in x.list[sapply(x.list, is.list)] <- 0 : 
  invalid subscript type 'list'

and getGroups() gives the following error: 

Error in if (xmlAttrs(r)[[1]] == 0) { : argument is of length zero

**Comment by skyprince999** [comment]
I think there are two issues over here: 
1) First I thought the app was not responding because it didn't have the proper permission. In the application details page --> OAuth User Agreement -> Default scope. The default setting is r_basicprofile. I updated this by checking the r_fullprofile, r_network, rw_groups, r_emailaddress & r_contactinfo checkboxes. 
1) When I run the inOAuth() method, the authorization token that is returned is not the recent authorization key+secret. viz. oauth_token and oauth_token_secret are different. I changed this to the current authorization key by: 

my.auth$credentials$oauth_token = (my_oauth_token from Developer page)
my.auth$credentials$oauth_token_secret = (my_oauth_token secret)

and then it works!

**Comment by skyprince999** [comment]
actually I get the correct tokens if I include the  cache=FALSE  parameter in the oauth1.0_token() call.

oauth1.0_token(linkedin,myapp,cache=FALSE)

**Comment by mpiccirilli** [comment]
I'm glad you pointed this out.  
- I updated the auth function to include an api and secret key for this package so users don't need to create their own developer application.  I included this already in the Readme. 
- If users decided to create their own developer application, they can use the same auth function, but must have all the 'Scope' parameters selected for their application.
- If you switch from the default application credentials to your own application's credentials, you should be prompted to authorize the new app, returning an updated token.  

I will include the last two bullet points in the Readme, but I will leave this issue open for now because I want to make sure the last bullet is working properly.

**Comment by skyprince999** [comment]
This is in continuation with my mail. I understand, that the code is checking if any previous authorization request has been made.  But it's returning a NULL argument with the following error(when it's executed for the first time):

Error in if (list.files(getwd(), all.files = TRUE, pattern = ".httr-oauth") ==  : 
  argument is of length zero

I updated it with a if(!is.null(list.file(.....)=='.httr=oauth'){.....} , argument and it works fine!

Other optional points are: To include the httr & XML libraries and you could take the linkedin,myapp and token intialization outside any of the condition loops, this reduce the number of lines in the code!

**Comment by mpiccirilli** [comment]
- I need to investigate whether is.null, or even if this method in general is the best way to check for prior authorizations. I will look into it this weekend. 
- When building a package, libraries are called in from the dependencies section of the DESCRIPTION file.
- You're right, I don't need those variables listed 3x.

**Comment by alevashov** [comment]
Hi there

I experienced the same problem with skyprince999

When I try to authorise my own app via inOAuth function (app name and keys are defined) I am getting error:
Error in if (list.files(getwd(), all.files = TRUE, pattern = ".httr-oauth") ==  : 
  argument is of length zero

I had previous authorisation in the same session (used httr)

**Comment by mpiccirilli** [comment]
I'm currently traveling, but I'll have time to take a look at it this weekend -- long overdue.  My apologies for the delay on this one.

**Comment by alevashov** [comment]
that is great, looking forward to try Rlinkedin again

**Comment by oristides** [comment]
same error when I use  may own app the function 

in.auth <- inOAuth(app_name, consumer_key, consumer_secret)

"Error in if (list.files(getwd(), all.files = TRUE, pattern = ".httr-oauth") ==  : 
  argument is of length zero"

when i try to use the default app. there is a error tht is worst. R breaks down. 

> in.auth <- inOAuth()
> Use a local file to cache OAuth access credentials between R sessions?
> 1: Yes
> 2: No

I use Yes (or  no). and then it take me to the authorization page. I accept and then R breaks down and the new webpage ' http://localhost:1410/?oauth_token=75--dccb73ee-f980-4353-a419-d226a0971bc3&oauth_verifier=92973"
and doe'snt exist.

if somebody can help with this I appreciate

**Comment by mpiccirilli** [comment]
@oristides My apologies, I will fix this tonight.

**Comment by ffgama** [comment]
in.auth <- inOAuth(app_name, consumer_key, consumer_secret)
Error: could not find function "inOAuth"

i'm use windows 8.1 64 bits, i also tried to last version ubuntu unsuccessfully  :(

**Comment by mpiccirilli** [comment]
@ffgama after you installed the package, did you call it into memory with either `require(Rlinkedin)` or `library(Rlinkedin)`?

**Comment by mpiccirilli** [comment]
@skyprince999 @ffgama @oristides @alevashov I've fixed the `inOAuth()` function (_finally_), it should be working fine now.  Please check it out and confirm, I'll close this issue.

**Comment by ffgama** [comment]
Hello @mpiccirilli, yes i am. I do all begin steps that you described, so:
require(devtools)
install_github("mpiccirilli/Rlinkedin")
require(Rlinkedin) 

Can you help me? Thanks >)

**Comment by RobertReynoldson** [comment]
inOAuth works for me now that I've gotten this latest fix. Thank you.

**Comment by oristides** [comment]
whwn i apply
in.auth <- inOAuth(app_name, consumer_key, consumer_secret)

then: 
If you've created you're own application, be sure to copy and paste the following into 
 'OAuth 2.0 Redirect URLs' in the LinkedIn Application Details: http://localhost:1410/ 
 When done, press any key to continue...

I press an then

Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

I use yes or no.. the result is the same. it shows an athorization webpage, then i athorize it.
and

The webpage is not found (http://localhost:1410/?oauth_token=75--78e8abee-8978-4dfa-955d-976534e8f53c&oauth_verifier=47231)  and R crash out.

it lea

**Comment by mpiccirilli** [comment]
@oristides Are you using your own application credentials?  If so, have you pasted  "http://localhost:1410/" in the **OAuth 2.0 Redirect URLs** dialog box in your application?  If you're unsure, here's a step-by-step tutorial: http://thinktostart.com/analyze-linkedin-with-r/

**Comment by oristides** [comment]
Yes, was pasted. All checks. I used the step by step.

![lnikedin](https://cloud.githubusercontent.com/assets/11547862/6756092/5cc0b292-cf06-11e4-86ae-b021b17997bf.png)

**Comment by mpiccirilli** [comment]
Have you re-installed the package since I pushed updates last night? 

I've tried the authorization in both RStudio and standard R environments, works in both for me. Looks like you're running standard R environment, have you tried on RStudio? 

If it still doesn't work, maybe try re-installing `httr` and `httpuv` (Rlinkedin is dependent on them for the oauth process and get called in when the package is loaded).  

Let me know if any of these work.

**Comment by oristides** [comment]
I tried reinstall packages, Rlinkedin, httr, httpuv, Rstudio, R alone. The same problem. firefox goes to the page for athorization, i athorize acces then R crash out and firefox or chrome doesn't find website.

I got a question, after allow ahtorization page what has to appear?

**Comment by mpiccirilli** [comment]
@oristides what do you mean by "R crash out"?  What exactly happens?

**Comment by mpiccirilli** [comment]
@oristides also make sure you have local host server enabled. You can find the option somewhere in the Control Panel.

**Comment by oristides** [comment]
Thanks, was that!. Enable localhost server in windows. it wasn't enabled. mmm the problem if is not enabled R stops.

Thanks!

**Comment by dalvimegha** [comment]
Hi ,

> in.auth <- inOAuth()
> If you've created you're own application, be sure to copy and paste the following into 
>  'OAuth 2.0 Redirect URLs' in the LinkedIn Application Details: http://localhost:1410 
>  When done, press any key to continue...
> Use a local file to cache OAuth access credentials between R sessions?
> 1: Yes
> 2: No

Selection: 1
Adding .httr-oauth to .gitignore
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Forbidden (HTTP 403).

I am facing this issue .
Please let me know where am i going wrong.

**Comment by mpiccirilli** [comment]
@dalvimegha I will check this out over the weekend. Apologies for the delay.

**Comment by dalvimegha** [comment]
Hi Michael,

I get the mentioned error when I use  i_n.auth <- inOAuth() in R .If I use
in.auth<-inOuth(app_name,consumer_key,consumer_secret) It does connect
and authorize me to LinkedIn_.

Also In the example as provided by one of the tutorials
my.connections <- getMyConnections(in.auth) doesn't work for me and gives
an error XML.

I need the LinkedIn posts  data for all the users for my course project and
I am not able to find it anywhere.

It would be a great help with any information on this.

Thanks & Regards,
Megha Dalvi
