### ISSUE TITLE
Error in UseMethod("xpathApply") 

### ISSUE THREAD

**Issue by johnfrombluff** [mpiccirilli/Rlinkedin#20]
Hi, thank for this package. If you're still working on it, I've run into an issue. I'm a reasonably competent R programmer, so if you can be as technical as you like describing the cause of this issue or asking for more information. I could also have a crack at fixing the code if that's required, and you give me a clue where to start ;-)

Here is what happens:

> require( Rlinkedin )
> in.auth <- inOAuth( "RConnectionExplorer", "XXX", "XXX" )
> If you've created you're own application, be sure to copy and paste the following into 
>  'OAuth 2.0 Redirect URLs' in the LinkedIn Application Details: http://localhost:1410/ 
>  When done, press any key to continue...
> my.connections <- getMyConnections(in.auth)
> Error in UseMethod("xpathApply") : 
>   no applicable method for 'xpathApply' applied to an object of class "c('xml_document', 'xml_node')"

Any ideas?

**Comment by mpiccirilli** [comment]
@johnfrombluff this function is no longer available to the open API.  Please see the main GitHub README for available functions.  I've updated the functions to include an input to identify LinkedIn Partners -- if this is set to zero then it will notify the user the function is no longer available
