### ISSUE TITLE
doesn't oauth out of the box

### ISSUE THREAD

**Issue by isomorphisms** [mpiccirilli/Rlinkedin#21]
I've added `http://localhost:1410/` to https://www.linkedin.com/developer/apps/123456789/auth. I open http://localhost:1410/ when I am asked by `inOAuth()` to authenticate in the browser.  Browser says `Authentication complete. Please close this page and return to R.` When I do so R says 

```
If you've created you're own application, be sure to copy and paste the following into 
 'OAuth 2.0 Redirect URLs' in the LinkedIn Application Details: http://localhost:1410/ 
 When done, press any key to continue...
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Error: Authentication failed.
```

**Comment by mpiccirilli** [comment]
The credentials on the CRAN version need to be updated.  I've updated the credentials on the GitHub version, I will be pushing the new version up to CRAN this week.

**Comment by svaditya** [comment]
I still get the same error. Tried installing both cran and github version. Any resolution?
