### ISSUE TITLE
package still working?

### ISSUE THREAD

**Issue by georgiamoon** [mpiccirilli/Rlinkedin#23]
Hi, I was following some of your steps and wondering if the package is still working? We're doing some research on jobs, and it'd be great to use this library, but I haven't succeeded in having any of the queries work. cc @natmey

**Comment by mpiccirilli** [comment]
@georgiamoon most of the functionality of the package was killed in May 2015 by LinkedIn when they closed a majority of their endpoints to the public.  

Only three functions in the package remain available to the public. These three are listed at the top of the README.

Are you a part of their partners program?  If not, then you will not be able to use the jobs related functions.

**Comment by georgiamoon** [comment]
@mpiccirilli thanks for the update -- that was what I had figured, but wanted to ask just in case! Good to know about the jobs functions and the partners program, I think I applied, but waiting to hear back.
