### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by Huntavius** [mpiccirilli/Rlinkedin#24]
Hello,

Thanks for making the package. I am trying to run this on an office computer so I'm guessing its something to do with our security but wanted to see if anyone had similar issues / bright ideas. I am getting the following error whether I use the default key or my developer key. Appreciate any help I can get.

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds

**Comment by mpiccirilli** [comment]
Hi Hunter, thanks for asking.  You most likely need to set your proxy to get past the firewall.  If you cannot set your proxy you may need to request your Information Security department to whitelist the specific base URLs for the API. 

This SO post may be helpful: https://stackoverflow.com/questions/6467277/proxy-setting-for-r

**Comment by Huntavius** [comment]
Yes you are right.  Figured out it its the firewall. Proxy server and whitelist weren't good options for me but I had success with connecting via wifi and not connecting vpn.  Not perfect but gets it done.  Thanks again.
