### ISSUE TITLE
Fail to connect to LinkedIn 

### ISSUE THREAD

**Issue by dash00** [mpiccirilli/Rlinkedin#4]
Hi 

I tried using your dev to connect to my linkedin profile using R but it failed at the very first step. Here are the details : 

> packageVersion("Rlinkedin")
> [1] ‘0.1’
> sessionInfo()
> R version 3.1.1 (2014-07-10)
> Platform: x86_64-pc-linux-gnu (64-bit)
> 
> locale:
>  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8  
>  [4] LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8  
>  [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C  
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] Rlinkedin_0.1  httpuv_1.3.2   XML_3.98-1.1   httr_0.6.1     devtools_1.7.0
> 
> loaded via a namespace (and not attached):
> [1] bitops_1.0-6     digest_0.6.8     R6_2.0.1         Rcpp_0.11.4      RCurl_1.95-4.5   rsconnect_0.3.76
> [7] stringr_0.6.2    tools_3.1.1  

My code : 

> require(Rlinkedin)
> app_name <- "XXXXXX"
> consumer_key <- "XXXXXXX"
> consumer_secret <- "XXXXXXX"
> in.auth <- inOAuth(app_name, consumer_key, consumer_secret)

The error  :  

> Error in if (list.files(getwd(), all.files = TRUE, pattern = ".httr-oauth") ==  : 
>  argument is of length zero

Using `debug(inOAuth)` it fails at the line 14 of the function inOAuth when testing `if (list.files(getwd(), all.files = TRUE, pattern = ".httr-oauth") == ".httr-oauth") {`. As i start from zero, I don't have any ".httr-oauth" file in my directory ....

Thanks for considering this issue
JC

**Comment by mpiccirilli** [comment]
@dash00 My apologies, I started a new job a few weeks ago and haven't given this package much attention lately.  I will take a look at this issue tonight.  I believe the other open issue is related as well.

**Comment by mpiccirilli** [comment]
@dash00 I just pushed a commit to fix this issue.  Please re-install the package from GitHub, and confirm it's working.

**Comment by dash00** [comment]
@mpiccirilli It works pretty well for me, thank you for this patch ! (fixed)
