### ISSUE TITLE
error when calling getMyConnections

### ISSUE THREAD

**Issue by adfi** [mpiccirilli/Rlinkedin#5]
Hi, I was trying out your package and received the following error when calling getMyConnections:
Error in x.list[sapply(x.list, is.list)] <- NA : 
  invalid subscript type 'list'

I followed the instructions in the ReadMe. Getting profile info works but the same error appears when getting connections profile info.

**Comment by mpiccirilli** [comment]
Both work OK for me.  Can you post your code?

**Comment by adfi** [comment]
`library(Rlinkedin)`
`in.auth <- inOAuth(appname, client, secret)`
`my.connections <- getMyConnections(in.auth)`
Error in x.list[sapply(x.list, is.list)] <- NA : 
  invalid subscript type 'list'

I'm on R verstion 3.1.1

**Comment by mpiccirilli** [comment]
This may be a silly question, but does the account you're creating an authorization for have connections? 

Also, if you haven't installed the package recently you may want to re-install it.

**Comment by adfi** [comment]
I installed the package yesterday with devtools. I've ticked all the boxes for app permissions:
![capture](https://cloud.githubusercontent.com/assets/1760262/7488826/a3df82d2-f3cf-11e4-9141-25add7d2b50a.PNG)

When I run the inOAuth command I get the following:
![capture2](https://cloud.githubusercontent.com/assets/1760262/7488836/d17d9db4-f3cf-11e4-866c-8f032a032e4a.PNG)

And in the browser I'm requested to give permission via my LinkedIn account.

**Comment by adfi** [comment]
any idea yet? should I try it on a different system or different R version or different LinkedIn account?

**Comment by mpiccirilli** [comment]
Try on another account if you can, I haven't been able to replicate issue on these two functions.

LinkedIn is updating their API access tomorrow so I may need to update some of these functions regardless.

**Comment by wilmeragsgh** [comment]
hey! i had the same issue and i solved by using in.auth <- inOAuth() instead of my credentials and it works fine

**Comment by adfi** [comment]
Thanks @wilmeragsgh , that worked! Still don't know what caused the initial problem but I guess this is the workaround.

**Comment by lunmei** [comment]
in.auth <- inOAuth() don't work for me. I got the error : 
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission) : 
  client error: (403) Forbidden

What's R version did you guys use?

**Comment by lunmei** [comment]
If I use my own keys, the in.auth works, getprofile works, but getconnections returned following error: 
Error in x.list[sapply(x.list, is.list)] <- NA : 
  invalid subscript type 'list'

**Comment by lunmei** [comment]
Linkedin seems recently changed the default application permission. I only have five to select
![test1](https://cloud.githubusercontent.com/assets/8219370/7904047/2087b908-07bc-11e5-830c-1ed8fd4bd24b.png)

**Comment by mpiccirilli** [comment]
@lunmei LinkedIn removed many of the API endpoints on May 12th.  I haven't had a chance to remove the functions in the package yet, but you can find what changed here: https://developer.linkedin.com/support/developer-program-transition

**Comment by lunmei** [comment]
Hi, Michael,

Thank you so much for your response. Yeah, it's too bad I am just a few
weeks late. Do you have other suggestion to get linkedin data?

Best,
lunmei

**Comment by kartucson** [comment]
Hi Michael, 

I had the same issues. It would be great if you can modify the packages to include the new linkedin API. Thanks!

**Comment by mmeloon** [comment]
@mpiccirilli I'm sure you're a busy guy, but it might be a good idea to update the Reference Manual on CRAN to let people know these functions don't work anymore.

**Comment by sdaulesvb** [comment]
Too bad, do we have a fix for this?

**Comment by HinChou** [comment]
Agree with mmeloon,  it will be a nice idea to have a update about the functions. Anyway, thank you for your work Michael.
