### ISSUE TITLE
Function GetMyConnections() in Rlinkedin pacakage is not working

### ISSUE THREAD

**Issue by pakhi18** [mpiccirilli/Rlinkedin#7]
> n.auth <- inOAuth(application_name="xx", consumer_key="xx", consumer_secret="xx")
> If you've created you're own application, be sure to copy and paste the following into 
>  'OAuth 2.0 Redirect URLs' in the LinkedIn Application Details: http://localhost:1410/ 
>  When done, press any key to continue...
> Use a local file to cache OAuth access credentials between R sessions?
> 1: Yes
> 2: No

Selection: 1
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.

> my.connections <- getMyConnections(n.auth)
> The following error is occuring 
> Error in x.list[sapply(x.list, is.list)] <- NA : 
>   invalid subscript type 'list'

**Comment by mpiccirilli** [comment]
@pakhi18 please read the [main page](https://github.com/mpiccirilli/Rlinkedin). I've listed which functions in the package are still available after LinkedIn changed their API policy on May 12th. `getMyConnections()` falls under the **Not Available** category :)

**Comment by pakhi18** [comment]
Thank you . Can you please send me the link of the main page you are
talking about. It would be of great help

**Comment by mpiccirilli** [comment]
https://github.com/mpiccirilli/Rlinkedin
