### ISSUE TITLE
unlistwithNAs

### ISSUE THREAD

**Issue by hopeful-coder** [mpiccirilli/Rlinkedin#8]
Hi. Excellent code job. The one issue I am having is when I am trying to use getMyConnections(token), I get an error message relating to the unlistwithNAs portion of the code. Here is the error message with the traceback. 

Error in x.list[sapply(x.list, is.list)] <- NA : 
  invalid subscript type 'list'

4: unlistWithNAs(nodes, "./id")
3: data.frame(id = unlistWithNAs(nodes, "./id"), fname = unlistWithNAs(nodes, 
       "./first-name"), lname = unlistWithNAs(nodes, "./last-name"), 
       headline = unlistWithNAs(nodes, "./headline"), industry = unlistWithNAs(nodes, 
           "./industry"), area = unlistWithNAs(nodes, "./location/name"), 
       country = unlistWithNAs(nodes, "./location/country/code"), 
       api_url = unlistWithNAs(nodes, "./api-standard-profile-request/url"), 
       site_url = unlistWithNAs(nodes, "./site-standard-profile-request/url")) at #4
2: connectionsToDF(q.content) at #7
1: getMyConnections(in.auth)

I presume that this is regarding the line of code in the error message. I hope we can fix this quickly!

Thank you!!!!
Great work!

**Comment by hopeful-coder** [comment]
I tried messing around with the unlistwithNAs source code, but to no avail. I believe the error is occurring because we are trying to subset using a list. sapply(x.list,is.list) is returning a list when I assume you are looking for a logical vector. I hope we can solve this soon.

**Comment by mpiccirilli** [comment]
@cousyman this issue related to #7, the endpoint for this function (http://api.linkedin.com/v1/people/~/connections) is no longer available on their open API.  You could probably use the function if you applied and gain acceptance to their Partnership program -- I applied for the purpose of keeping the package up-to-date but I was rejected. 

There's a list of functions that are still available for their open API listed on the main [Readme](https://github.com/mpiccirilli/Rlinkedin) of this repo. 

I think i'm going to update the functions that are no longer available to their open API to include an input to indicate whether the user is a partner, and stop the function if the user is not a Partner to avoid any confusion.  For example:
- _function(..., partner = 1)_ for a user who is a Partner
- _function(..., partner = 0)_ for a user who is not a Partner (default)

I'll open a separate issue for this.
